// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — Neon's pooled/PgBouncer
    // endpoint doesn't support the session-level advisory lock `migrate deploy`
    // takes, which causes it to time out (P1002). The Vercel-Neon integration
    // auto-provides DATABASE_URL_UNPOOLED for exactly this case.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
